### ISSUE TITLE
The vsphere permissions list has an unknown permission 

### ISSUE THREAD

**Issue by eshanks16** [pivotal-cf/docs-ops-manager#91]
The link https://docs.pivotal.io/platform/ops-manager/2-10/vsphere/vsphere-service-account.html shows the permission VirtualMachine.Config.Unlock needed for minimum permissions.

This permission can't be found in the recent documentation.
6.5 - https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.security.doc/GUID-FEAB5DF5-F7A2-412D-BF3D-7420A355AE8F.html
7.0 - https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-FEAB5DF5-F7A2-412D-BF3D-7420A355AE8F.html

**Comment by seviet** [comment]
Hi @eshanks16! thanks for reporting this. I did a little digging and found that permission listed in the vSphere 6.0 docs here: https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.security.doc/GUID-FEAB5DF5-F7A2-412D-BF3D-7420A355AE8F.html. Looks like this permission was removed from docs starting in vSphere 6.5. 

Since we made the minimum version of vSphere 6.5 starting in Ops Manager/TAS for VMs v2.9, we can remove the permission from the list in Ops Man v2.9 and later docs and in earlier Ops Man docs, we can note that the permission applies to vSphere 6.0 only.

**Comment by seviet** [comment]
Update: I've updated docs to remove that permission from v2.9 and v2.10 docs https://docs.pivotal.io/ops-manager/2-10/vsphere/vsphere-service-account.html#vm -- and added a note about vSphere 6.0 to to v2.8 and earlier docs. Closing-- if you need anything else, feel free to reopen up the issue.
